dist: xenial
language: java
java:
- openjdk11
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.cache/yarn"
before_install:
- nvm install '12'
install: true
before_script:
- yarn global add @conveyal/maven-semantic-release semantic-release@15
script:
- mvn package
after_success:
- bash <(curl -s https://codecov.io/bash) -s target-unit-test-results -F unit_tests
- |
  semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow --dev-branch=dev --skip-maven-deploy
  if [[ "$TRAVIS_BRANCH" = "master" ]]; then
    bash <(curl -s https://codecov.io/bash) -C "$(git rev-parse HEAD)" -s target-unit-test-results -F unit_tests
    bash <(curl -s https://codecov.io/bash) -C "$(git rev-parse HEAD^)" -s target-unit-test-results -F unit_tests
  fi
before_deploy:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- export BRANCH_CLEAN=${BRANCH//\//_}
- mkdir deploy
- ls target/*.jar
- cp target/otp-middleware-*.jar deploy/
- cp target/otp-middleware-*.jar "deploy/otp-middleware-latest-BRANCH_CLEAN.jar"
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIA2YG5XQ2YJDTPRQ7Z
  secret_access_key:
    secure: PCGi5btTWXmvhABKbpbccDG95wNGhsmmBpOJuGNOCCdIT2xMNQnrOUDIe4yfIO493sOUns85TVz9wL4w5uX8YAYARB7shS1+PRQy+V0qZQKx1D2hrAraA6Z2e3wmyxYeweHb/wwasYs1GwTyMIvUGclsyPQ5md4P5dKCYs07hFdJU6DOugrtAGYfnBObotjyIU9vyEDLM9pRm0v4vlO8fOxFvyevx6uJH2T+nYUdu/UqirnWMUSY6caQ79Y7xIbsxbnE13KaFkBBRDzQF/jXkcI4DXjmQXMb1TIx1Fb6mjZm6eISERoZBxn5EVWbcgcGN2gg42skXOAuoXvPekLTWqHM6Zr9dTQfPLB7kpZxkbEBr1DK4LUwhp/p7xSalf9axN20GzmobXz/rsAeL46t9BCM4jbl0Ryi/y04FfoQ4qMyLoUfHoMqkcdLl/W4g2wxaxXHvUk9Wyfeyt6btk0zL8ffIlngl3Rwt6GmFljn3w9ux/cZrNtzcKPWqqWccsT61/nhlezaCHkcso9HZzbG9fEfyb1buQX+GeHCOl+BgbkTpSWwu8qqYMVgmjgcviBUDYELK089QW1xj2BN+ZPvJDfLBadSxNOHH6yudtfrJYZnwx+dw2AUMBWkrv0C+aIUI0NChige2a9WKycoeiAv4sRZvczZwZrTSzsWI+Kz248=
  bucket: otp-middleware-builds
  local-dir: deploy
  acl: public_read
  on:
    repo: ibi-group/otp-middleware
    all_branches: true
