os: linux
dist: xenial
language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.cache/yarn"
before_install:
- nvm install '12'
install: true
before_script:
- yarn global add @conveyal/maven-semantic-release semantic-release@15
script:
- mvn package
after_success:
- bash <(curl -s https://codecov.io/bash) -s target-unit-test-results -F unit_tests
- |
  semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow --dev-branch=dev --skip-maven-deploy
  if [[ "$TRAVIS_BRANCH" = "master" ]]; then
    bash <(curl -s https://codecov.io/bash) -C "$(git rev-parse HEAD)" -s target-unit-test-results -F unit_tests
    bash <(curl -s https://codecov.io/bash) -C "$(git rev-parse HEAD^)" -s target-unit-test-results -F unit_tests
  fi
before_deploy:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- export BRANCH_CLEAN=${BRANCH//\//_}
- mkdir deploy
- ls target/*.jar
- cp target/otp-middleware-*.jar deploy/
- cp target/otp-middleware-*.jar "deploy/otp-middleware-latest-$BRANCH_CLEAN.jar"
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIA2YG5XQ2YJDTPRQ7Z
  secret_access_key:
    secure: LCD8DBvwPCkKXH+YWk0oZaQLvGSXbHb2/QcvEGnb4q6eaNASuesCWVc5t/KwzdA1SLcM4RNs3xH3o4oo3AYy/ARX+Ouf0yHal6p7WDXYceuo/yrsxt1NxrVDDRxgRCCmkVp8TpKV3tTH7lFAGipFT1XT+a1GkLfgji2OnJYsgercSS7WJHg7nU3c4PSNSXWbh3cp78qWcmKmSNN+D5JqZfNOM2hgldibcr+wspNk4eirgxvZpgcUfNbit/Si+Lz74lMLla75AFXs5HoD/kObrNgaycIFcUpO0+SWJ1loDW5T2KWZAAbbKl7OTh6npX93Gz82naDNH0g3vHqtPwlQa/j4lNpBlo/ArmfMSbpmc15BnEKdt+w1BOLZnZmJPRJhRW5qGmQDStRR6axJiBmYuIqj1lan5L38fG5XM/M4sAKJo9rs2uAm578NS4e6rT8zrY1bYQw9+0P+5CP70VgACZg+ibMjW2f6jNCp9Dg4G4W38+n0wwwbIJzYPieap2sAgqRLNHWod8WMXFUNEOJyNRE2kXc8ZOq7JnhOkBdGgz4JgPGz6xV55HwXjOso13V1q4us85YIZA+AG1CI6JGjoNm3zQNnlzETztd7589y8N6IFQ22U+XkFLEQZuZTo43+UTgAUFf9bKoYWAMwwvGquCeS/2xurXLyKhteGH6aEBw=
  bucket: otp-middleware-builds
  local_dir: deploy
  acl: public_read
  on:
    repo: ibi-group/otp-middleware
    all_branches: true
