# To generate the full OpenAPI (Swagger) file, use command
# swagger-inline "**/*.java" --base api-base.yaml > api.yaml
# or
# swagger-inline "**/*.java" --base api-base.yaml --format .json > api.json
openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "otp-middleware"
  license: 
    name: "MIT"
components:
  # Reusable response headers


  # Reusable request parameters
  parameters:
    AWSAuthHeaderRequired:
      deprecated: true
      description: Use the proper authorization manager instead of passing this individual header.
      name: Authorization # Required for AWS integration.
      in: header
      required: false
      schema:
        type: string
    IDParameter:
      name: id
      in: path
      description: The ID of the entity to search.
      required: true
      schema:
        type: string

  # Reusable response bodies
  responses:
    # For malformed credentials.
    401Unauthorized:
      description: API key or token is missing or could not be validated.
      headers:
        WWW_Authenticate:
          schema:
            type: string
    # For enabling CORS.
    AllowCORS:
      description: Success
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
    # For returning one AdminUser
    AdminUser:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AdminUser"
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
    # For returning one ApiUser
    ApiUser:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiUser"
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
    # For returning one OtpUser
    OtpUser:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OtpUser"
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string

  requestBodies:
    AdminUser:
      description: The AdminUser entity to add or update.
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AdminUser"
    ApiUser:
      description: The ApiUser entity to add or update.
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiUser"
    OtpUser:
      description: The OtpUser entity to add or update.
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OtpUser"

  securitySchemes:
    # For Auth0Bearer below: As of July 2020, AWS API Gateway will incorrectly warn
    # that http is an invalid type. AWS will drop this entry on import.
    # Outside of AWS, however, this is the proper form for the documenting a bearer token requirement.
    Auth0Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKey:
      type: apiKey
      in: header
      name: x-api-key

# You would normally apply the security globally to all operations
# However, as of July 2020, AWS API Gateway requires spelling out ApiKey and Auth0Bearer authorizations
# explicitly in all api paths that need them.
# security:
#  - Auth0Bearer: []
#  - ApiKey: []
tags:
  - name: api/admin/user
    description: Interface for managing admin dashboard users (admin access only).
  - name: api/secure/application
    description: Interface for managing API users (the application developers).
  - name: api/secure/logs
    description: Interface for retrieving logs.
  - name: api/secure/user
    description: Interface for managing OTP users (the general public).
