version: '3.8'
services:
  otp-middleware:
    build: .
    command: --endpoints yes
    ports:
      - "4567:4567"
    volumes:
      - type: bind
        source: ./configurations/default/env.yml
        target: /config/env.yml
  mongo:
    volumes:
      - type: bind
        source: /opt/homebrew/var/mongodb
        target: /data/db
    ports:
      - "27017:27017"