version: '3.8'
services:
  otp-middleware:
    image: milesgrantibigroup/otp-middleware-test:latest
    ports:
      - "4567:4567"
    volumes:
      - type: bind
        source: ./configurations/default/env.docker.yml
        target: /config/env.yml
  mongo:
    image: mongo
    restart: always