version: '3.8'
services:
  otp-middleware:
    image: public.ecr.aws/s2a5w2n9/otp-middleware:latest
    ports:
      - "4567:4567"
    volumes:
      - type: bind
        source: ./configurations/default/env.docker.yml
        target: /config/env.yml
      - type: bind
        source: ./configurations/default/aws-credentials
        target: /root/.aws/credentials
      - type: bind
        source: ./configurations/default/aws-config
        target: /root/.aws/config
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always