package org.opentripplanner.middleware.docs;

import org.opentripplanner.middleware.OtpMiddlewareMain;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.opentripplanner.middleware.docs.PublicApiDocGenerator.getSwaggerDocsAsString;

/**
 * This class is solely intended to be executed on a development machine
 * to update the version-controlled spark-swagger output.
 */
public class VersionControlledSwaggerUpdater {
    public static final String SWAGGER_CONTROLLED_FILE = "src/main/resources/spark-swagger-controlled-output.yaml";

    private static final Logger LOG = LoggerFactory.getLogger(VersionControlledSwaggerUpdater.class);

    public static void main(String[] args) throws IOException, InterruptedException {
        OtpMiddlewareMain.main(new String[0]);
        updateSwaggerDocs();

        System.exit(0);
    }

    /**
     * Performs an update to the Swagger docs file located at {@link #SWAGGER_CONTROLLED_FILE},
     * which is used by {@Link SwaggerTest} for keeping the docs file up-to-date.
     */
    public static void updateSwaggerDocs() throws IOException, InterruptedException {
        String autoGeneratedSwagger = getSwaggerDocsAsString();
        Path versionControlledSwaggerFile = new File(SWAGGER_CONTROLLED_FILE).toPath();
        Files.writeString(versionControlledSwaggerFile, autoGeneratedSwagger);

        LOG.info("The version-controlled swagger document has been updated.");
    }
}
