name: Maven CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Maven Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.m2
          key: maven-local-repo
      - name: Build with Maven (run unit tests)
        run: mvn --no-transfer-progress package
        env:
          AWS_API_SERVER: localhost:4567
      - name: Run E2E tests
        run: mvn --no-transfer-progress test
        env:
          RUN_E2E: true

      # if this point it reached, the CI build has succeeded
      - name: Codecov
        uses: codecov/codecov-action@v1.2.0
        continue-on-error: true
      - name: Prepare files for deployment to s3
        run: ./scripts/prep-for-deploy-from-github-actions.sh
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy deployment files to the otp-middleware-builds bucket
        run: |
          aws s3 sync ./deploy s3://otp-middleware-builds --acl public-read