name: Maven CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OTP_ADMIN_DASHBOARD_NAME: OTP Admin Dashboard
      OTP_ADMIN_DASHBOARD_FROM_EMAIL: OTP Admin Dashboard <no-reply@email.com>
      OTP_UI_NAME: Trip Planner
      AUTH0_API_CLIENT: ${{ secrets.AUTH0_API_CLIENT }}
      AUTH0_API_SECRET: ${{ secrets.AUTH0_API_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_PROFILE: default
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
      BUGSNAG_ORGANIZATION: ${{ secrets.BUGSNAG_ORGANIZATION }}
      BUGSNAG_PROJECT_NOTIFIER_API_KEY: ${{ secrets.BUGSNAG_PROJECT_NOTIFIER_API_KEY }}
      DEFAULT_USAGE_PLAN_ID: ${{ secrets.DEFAULT_USAGE_PLAN_ID }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      NOTIFICATION_FROM_EMAIL: ${{ secrets.NOTIFICATION_FROM_EMAIL }}
      NOTIFICATION_FROM_PHONE: ${{ secrets.NOTIFICATION_FROM_PHONE }}
      OTP_ADMIN_DASHBOARD_URL: ${{ secrets.OTP_ADMIN_DASHBOARD_URL }}
      OTP_API_ROOT: ${{ secrets.OTP_API_ROOT }}
      OTP_PLAN_ENDPOINT: ${{ secrets.OTP_PLAN_ENDPOINT }}
      OTP_TIMEZONE: ${{ secrets.OTP_TIMEZONE }}
      OTP_UI_URL: ${{ secrets.OTP_UI_URL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SPARKPOST_KEY: ${{ secrets.SPARKPOST_KEY }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_VERIFICATION_SERVICE_SID: ${{ secrets.TWILIO_VERIFICATION_SERVICE_SID }}

    steps:
      - uses: actions/checkout@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Maven Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.m2
          key: maven-local-repo
      - name: Add profile credentials to ~/.aws/credentials
        run: ./scripts/add-aws-credentials.sh
      - name: Build with Maven (run unit tests)
        run: mvn --no-transfer-progress package
      - name: Run E2E tests
        run: mvn --no-transfer-progress test
        env:
          RUN_E2E: true

      # if this point it reached, the CI build has succeeded
      - name: Codecov
        uses: codecov/codecov-action@v1.2.0
        continue-on-error: true
      - name: Prepare files for deployment to s3
        run: ./scripts/prep-for-deploy-from-github-actions.sh
      - name: Copy deployment files to the otp-middleware-builds bucket
        run: |
          aws s3 sync ./deploy s3://otp-middleware-builds --acl public-read